### ISSUE TITLE
Switch from MySql.Data to MySqlConnector

### ISSUE THREAD

**Issue by twerthi** [DbUp/dbup-mysql#8]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Description

MySql.Data is no longer compatible with MariaDB and fails when using MariaDB version 10+.  Research indicates that switching from MySql.Data to MySqlConnector will resolve this.

### What is the impact?

dbup using the dbup-mysql reference fails to execute against an MariaDB version 10+.

**Comment by vigur** [comment]
Is there a plan to merge PR related to this ticket in a near future ? We have a similar issue when certain versions of MariaDB are not compatible with  Oracle's MySql.Data connector and the best proposed solution by MariaDB team is to use MySqlConnector instead.
